### ISSUE TITLE
Windows Folders support

### ISSUE THREAD

**Issue by Pynx** [GanymedeTeam/ganymede-app#6]
Add the system we previously had on the Unity version

- All folders should be visible inside the downloaded guide list
- Search function should search into all folders
- When a result from the search bar is into a folder, we see the folder instead of the guide itself
- A small display should show where we are in the folders
- A button should allow us to leave a folder and reach its parent
- ALL GUIDES SHOULD BE DOWNLOADED IN THE ROOT FOLDER BY DEFAULT

**Comment by Pynx** [comment]
Here is an exemple of what is could look like 
![image](https://github.com/user-attachments/assets/0d4e747b-fbb6-4e3e-8078-1e9e6592fdc6)

**Comment by GoatFreezy** [comment]
- Be able to delete a folder from the application via a red button with a bin icon

**Comment by Kiyozz** [comment]
Closed by latest main 8016a9a40cc016803c5b8e70a819c98e83a53e64
